version: '3'
services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: keyist
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keyistuser
      MYSQL_PASSWORD: keyistpassword
    volumes:
      - './sql/script.sql/:/docker-entrypoint-initdb.d/script.sql'
